Theme generation pullout
No changes, just reorganization.

The default theme of liquidprompt has been ingrained in the
_lp_set_prompt() function. Add _lp_theme_prompt(),
_lp_theme_directory(), and _lp_theme_activate() to allow for themes to
override and do their own thing.

diff --git a/liquidprompt b/liquidprompt
--- a/liquidprompt
+++ b/liquidprompt
@@ -316,21 +316,6 @@ lp_activate() {
         LP_TITLE_CLOSE="$(printf '\a')"
     fi
 
-    # Default value for LP_PERM when LP_ENABLE_PERM is 0
-    LP_PERM=${LP_MARK_PERM}   # without color
-
-    ###################
-    # CURRENT TIME    #
-    ###################
-
-    # LP_TIME is set colored, with a space on the right side
-    if (( LP_ENABLE_TIME )); then
-        # Never changes
-        LP_TIME="${LP_COLOR_TIME}${_LP_TIME_SYMBOL}${NO_COL} "
-    else
-        LP_TIME=""
-    fi
-
     ###############
     # Who are we? #
     ###############
@@ -398,6 +383,8 @@ lp_activate() {
             alias _lp_shorten_path=_lp_set_dirtrim
         fi
     fi
+
+    _lp_theme_activate
 }
 
 #####################
@@ -979,22 +966,42 @@ _lp_title() {
     echo -nE "${LP_TITLE_CLOSE}${_LP_CLOSE_ESC}"
 }
 
-########################
-# Construct the prompt #
-########################
+#################
+# Default theme #
+#################
 
-_lp_set_prompt() {
-    # Display the return value of the last command, if different from zero
-    # As this get the last returned code, it should be called first
-    local -i err=$?
-    if (( LP_ENABLE_ERR && err != 0)); then
-        LP_ERR="$LP_MARK_SPACE$LP_COLOR_ERR$err$NO_COL"
+_lp_theme_activate() {
+    # Default value for LP_PERM when LP_ENABLE_PERM is 0
+    LP_PERM=${LP_MARK_PERM}   # without color
+
+    if (( LP_ENABLE_TIME )); then
+        # Never changes
+        LP_TIME="${LP_COLOR_TIME}${_LP_TIME_SYMBOL}${NO_COL} "
     else
-        LP_ERR=
+        LP_TIME=""
     fi
+}
 
-    # bash: execute the old prompt hook
-    eval "$LP_OLD_PROMPT_COMMAND"
+_lp_theme_directory() {
+    # LP_PERM: shows a ":"
+    # - colored in green if user has write permission on the current dir
+    # - colored in red if not
+    # - can set another symbol with LP_MARK_PERM
+    if (( LP_ENABLE_PERM )); then
+        if [[ -w "${PWD}" ]]; then
+            LP_PERM="${LP_COLOR_WRITE}${LP_MARK_PERM}${NO_COL}"
+        else
+            LP_PERM="${LP_COLOR_NOWRITE}${LP_MARK_PERM}${NO_COL}"
+        fi
+    fi
+}
+
+_lp_theme_prompt() {
+    if (( LP_ENABLE_ERR && lp_err != 0 )); then
+        LP_ERR="$LP_MARK_SPACE$LP_COLOR_ERR$lp_err$NO_COL"
+    else
+        LP_ERR=""
+    fi
 
     # left of main prompt: space at right
     if _lp_jobcount_color; then
@@ -1029,25 +1036,6 @@ _lp_set_prompt() {
         LP_SCLS=""
     fi
 
-    # if change of working directory
-    if [[ "${LP_OLD_PWD-}" != "LP:$PWD" ]]; then
-        # LP_PERM: shows a ":"
-        # - colored in green if user has write permission on the current dir
-        # - colored in red if not
-        # - can set another symbol with LP_MARK_PERM
-        if (( LP_ENABLE_PERM )); then
-            if [[ -w "${PWD}" ]]; then
-                LP_PERM="${LP_COLOR_WRITE}${LP_MARK_PERM}${NO_COL}"
-            else
-                LP_PERM="${LP_COLOR_NOWRITE}${LP_MARK_PERM}${NO_COL}"
-            fi
-        fi
-
-        _lp_shorten_path   # set LP_PWD
-
-        LP_OLD_PWD="LP:$PWD"
-    fi
-
     if _lp_find_vcs; then
         case "$lp_vcs_type" in
             # git, git-svn, git-vcsh
@@ -1066,7 +1054,7 @@ _lp_set_prompt() {
         source "$LP_PS1_FILE"
     fi
 
-    if [[ -z "$LP_PS1" ]]; then
+    if [[ -z "${LP_PS1-}" ]]; then
         # add time and jobs
         PS1="${LP_TIME}${LP_JOBS}"
         # add user, host and permissions colon
@@ -1091,6 +1079,34 @@ _lp_set_prompt() {
     else
         PS1=$LP_PS1
     fi
+}
+
+########################
+# Construct the prompt #
+########################
+
+_lp_set_prompt() {
+    # Display the return value of the last command, if different from zero
+    # As this get the last returned code, it should be called first
+    local -i lp_err=$?
+
+    # bash: execute the old prompt hook
+    eval "$LP_OLD_PROMPT_COMMAND"
+
+    # if change of working directory
+    if [[ "${LP_OLD_PWD-}" != "LP:$PWD" ]]; then
+        _lp_shorten_path   # set LP_PWD
+
+        _lp_theme_directory
+
+        # Prefix with 'LP:' to prevent Zsh with AUTO_NAME_DIRS enabled using
+        # this var as a name for the working directory, that will be used by
+        # the '%' and related prompt sequences.
+        # See https://github.com/nojhan/liquidprompt/issues/124 for details.
+        LP_OLD_PWD="LP:$PWD"
+    fi
+
+    _lp_theme_prompt
 }
 
 prompt_tag() {
